# Generated by Django 5.2.7 on 2025-10-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='입관일자'),
        ),
        migrations.AddField(
            model_name='member',
            name='admission_motivation',
            field=models.TextField(blank=True, verbose_name='입관 동기'),
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='나이(만)'),
        ),
        migrations.AddField(
            model_name='member',
            name='age_group',
            field=models.CharField(blank=True, choices=[('유치부', '유치부'), ('초등부', '초등부'), ('중등부', '중등부'), ('고등부', '고등부'), ('대학부', '대학부'), ('일반부', '일반부')], max_length=20, verbose_name='학년분류'),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A형'), ('B', 'B형'), ('O', 'O형'), ('AB', 'AB형'), ('RH-', 'RH-')], max_length=10, verbose_name='혈액형'),
        ),
        migrations.AddField(
            model_name='member',
            name='dan_rank',
            field=models.CharField(blank=True, max_length=50, verbose_name='단(품)급'),
        ),
        migrations.AddField(
            model_name='member',
            name='dan_rank_date',
            field=models.DateField(blank=True, null=True, verbose_name='단(품)급 취득일'),
        ),
        migrations.AddField(
            model_name='member',
            name='dan_rank_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='단(품)번호'),
        ),
        migrations.AddField(
            model_name='member',
            name='exercise_aptitude',
            field=models.TextField(blank=True, verbose_name='본인 운동 소질'),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='신장(cm)'),
        ),
        migrations.AddField(
            model_name='member',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='자택전화'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='관번'),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_job',
            field=models.CharField(blank=True, max_length=100, verbose_name='부모님 직업'),
        ),
        migrations.AddField(
            model_name='member',
            name='personality_description',
            field=models.TextField(blank=True, verbose_name='본인 성격'),
        ),
        migrations.AddField(
            model_name='member',
            name='religion',
            field=models.CharField(blank=True, choices=[('무교', '무교'), ('기독교', '기독교'), ('천주교', '천주교'), ('불교', '불교'), ('기타', '기타')], max_length=20, verbose_name='종교'),
        ),
        migrations.AddField(
            model_name='member',
            name='school_grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='학년/반'),
        ),
        migrations.AddField(
            model_name='member',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='학교명'),
        ),
        migrations.AddField(
            model_name='member',
            name='special_notes',
            field=models.TextField(blank=True, verbose_name='본인의 특기 사항'),
        ),
        migrations.AddField(
            model_name='member',
            name='training_reason',
            field=models.TextField(blank=True, verbose_name='수련 보낸 이유'),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='체중(kg)'),
        ),
        migrations.AddField(
            model_name='member',
            name='withdrawal_date',
            field=models.DateField(blank=True, null=True, verbose_name='퇴관일자'),
        ),
        migrations.AddField(
            model_name='member',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='직장전화'),
        ),
    ]
