# Generated by Django 5.2.7 on 2025-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_admission_date_member_admission_motivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', '자유게시판'), ('workout', '운동정보'), ('nutrition', '식단'), ('question', '질문'), ('success', '성공사례'), ('review', '리뷰')], default='general', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='제목'),
        ),
    ]
