# Generated by Django 5.2.7 on 2025-10-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_post_category_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='approval_status',
            field=models.CharField(choices=[('pending', '승인대기'), ('approved', '승인완료'), ('rejected', '거절됨')], default='approved', max_length=20, verbose_name='승인 상태'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인 일시'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='결제 수단'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='거절 일시'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='거절 사유'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
    ]
