# Generated by Django 5.2.7 on 2025-10-26 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_subscription_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='체육관명')),
                ('address', models.CharField(max_length=300, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('description', models.TextField(blank=True, verbose_name='소개')),
                ('logo', models.TextField(blank=True, verbose_name='로고 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '체육관',
                'verbose_name_plural': '체육관들',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_gym_only',
            field=models.BooleanField(default=False, verbose_name='내 체육관 전용'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.IntegerField(default=0, verbose_name='영상 길이(초)'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.TextField(blank=True, verbose_name='영상 URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', '자유게시판'), ('workout', '운동정보'), ('diet', '식단'), ('qna', 'Q&A'), ('notice', '공지사항'), ('review', '리뷰')], default='general', max_length=50, verbose_name='카테고리'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('image', models.TextField(verbose_name='이미지 URL')),
                ('link', models.TextField(blank=True, verbose_name='링크 URL')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='members.gym', verbose_name='체육관')),
            ],
            options={
                'verbose_name': '배너',
                'verbose_name_plural': '배너들',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.gym', verbose_name='소속 체육관'),
        ),
        migrations.AddField(
            model_name='post',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='members.gym', verbose_name='체육관'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.TextField(blank=True, verbose_name='이미지 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='members.gym', verbose_name='체육관')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항들',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
