# Generated by Django 5.2.7 on 2025-10-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_gym_post_is_gym_only_post_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='관리자 여부'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='최고관리자 여부'),
        ),
    ]
